# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/faea/HY509_V2_0/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
#    vendor/faea/HY509_V2_0/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
#    vendor/faea/HY509_V2_0/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
#    vendor/faea/HY509_V2_0/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
#    vendor/faea/HY509_V2_0/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so

PRODUCT_COPY_FILES += \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libBLPP.so:system/vendor/lib/libBLPP.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/lib/hw/gralloc.mt6589.so:system/vendor/lib/hw/gralloc.mt6589.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libbessound_mtk.so:system/lib/libbessound_mtk.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libmedia.so:system/lib/libmedia.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libdpframework_os.so:system/lib/libdpframework_os.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libdpframework_plat.so:system/lib/libdpframework_plat.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/faea/HY509_V2_0/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/faea/HY509_V2_0/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/faea/HY509_V2_0/proprietary/lib/libwapi.so:system/lib/libwapi.so \
    vendor/faea/HY509_V2_0/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/faea/HY509_V2_0/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/faea/HY509_V2_0/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/faea/HY509_V2_0/proprietary/bin/rild:system/bin/rild \
    vendor/faea/HY509_V2_0/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/faea/HY509_V2_0/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/faea/HY509_V2_0/proprietary/bin/hald:system/bin/hald \
    vendor/faea/HY509_V2_0/proprietary/bin/wlan_loader:system/bin/wlan_loader \
    vendor/faea/HY509_V2_0/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/faea/HY509_V2_0/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/faea/HY509_V2_0/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628_patch_e2_0_hdr.bin:system/etc/firmware/mt6628_patch_e2_0_hdr.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/modem.img:system/etc/firmware/modem.img \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v2_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v2_patch.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_rom.bin:system/etc/firmware/mt6628/mt6628_fm_rom.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v3_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v3_patch.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v1_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v1_patch.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v4_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v4_patch.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628/mt6628_fm_v5_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v5_patch.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628_ant_m1.cfg:system/etc/firmware/mt6628_ant_m1.cfg \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/catcher_filter.bin:system/etc/firmware/catcher_filter.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/mt6628_patch_e2_1_hdr.bin:system/etc/firmware/mt6628_patch_e2_1_hdr.bin \
    vendor/faea/HY509_V2_0/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg
PRODUCT_COPY_FILES += \
 vendor/faea/HY509_V2_0/proprietary/lib/libaudio.primary.default.so:system/lib/hw/audio.primary.mt6589.so$LINEEND
 vendor/faea/HY509_V2_0/proprietary/lib/hw/audio_policy.mt6589.so:system/lib/hw/audio_policy.mt6589.so
